Darlin serializations
HorizenLabs/marlin pull request #10
Opened 2021-04-16 14:25 UTC by DanieleDiBenedetto

2021-04-20 06:08 UTC, phoinic approved these changes

2021-04-26 09:11 UTC, UlrichHaboeck75 commented on src/ahp/prover.rs
> +            ProverMsg::EmptyMessage => 0u32.write(&mut writer),
We write a u32 zero for an empty message? If these four bytes (really four?) encode the length of the message than that's ok.

2021-04-26 09:18 UTC, UlrichHaboeck75 commented on src/data_structures.rs
> +    fn is_valid(&self) -> bool {
We could widen the notion of validity of a verifier key beyond just commitment checks, by some general checks on the index_info.

2021-04-26 09:20 UTC, UlrichHaboeck75 commented on src/data_structures.rs
> +        self.index_vk.is_valid()
The same here: we could add the checks that the arithmetizations of the R1CS matrices are correct, or at least do some lightweight checks as degree bounds, etc.

2021-04-26 09:22 UTC, UlrichHaboeck75 commented on src/data_structures.rs
> +            self.pc_proof.is_valid()
I expect that the checks here are just elementwise. We could do also some additional ones such as on the number of commitments and evaluations.

2021-04-26 09:28 UTC, UlrichHaboeck75 reviewed
As mentioned in my comments, we could elaborate on the notion of semantic validity of key material, etc., by some further cheap checks on metrics (the number of commitments, evaluations, the index info, etc.)

2021-04-27 14:10 UTC, UlrichHaboeck75 commented on src/ahp/prover.rs
> +
Shouldn't we assume throughout that ``ProverMsg`` is empty?

2021-04-27 14:13 UTC, UlrichHaboeck75 approved these changes
Very well written update!

2021-04-28 09:45 UTC, albertog78 requested changes

2021-04-28 09:45 UTC, albertog78 commented on src/data_structures.rs
> +        self.index_comms.serialize_uncompressed(writer)
index_info ?

2021-04-28 09:49 UTC, albertog78 approved these changes

2021-04-28 09:49 UTC, merged